### ISSUE TITLE
Question: Why use bespoke instead of reveal, strut, impress, etc ?

### ISSUE THREAD

**Issue by zckrs** [bespokejs/bespoke#67]
Hi,

I just discover bespoke through a presentation from @sokra ([here](https://github.com/sokra/slides)). And I like it.

But before go deep into I would ask you why you created bespoke instead of using other equivalents.

Note: no evil question here I'm just curious

***
ping @hsablonniere

**Comment by hsablonniere** [comment]
Hi @zckrs :smile: 

I cannot speak for @markdalgleish regarding *the Why* but I can give you facts and my own opinion :wink:.

bespoke was created in december 2012 as an HTML5 presentation microlib. Other popular presentation projects were created the year before: reveal.js (june 2011), dzslides (april 2011)... I wasn't using these at that time so I don't know if they were known enough not to consider building a new one.

The main focus of the project hasn't change: a very very small core and a wide ecosystem of plugins.

I use bespoke over other solutions because of this. I really think web based presentation tools are an opportunity to innovate and take some distance with the classic PowerPoint and Keynote presentations. Having a small core and being able to reuse and create plugins is -- in my opinion -- a great way to do this. As a speaker, I want to innovate and try new ideas to tell a story and teach concepts. Because bespoke comes without batteries included, I can tweak many stuffs to my needs (CSS, JavaScript behaviour...). That's what I'm looking for when building a presentation.

This approach also allow you to have a ready to use set of plugins that work for speakers that only want a quick solution. We have a [generator](https://github.com/bespokejs/generator-bespoke) for that. We're currently working on [a new version](https://github.com/bespokejs/generator-bespoke/pull/38).

In the end whether you choose to use bespoke or any other framework is a matter of authoring/speaking style and a matter of personal taste.

**Comment by zckrs** [comment]
Thanks a lot @hsablonniere 

You confirmed my opinion, bespoke is a right micro framework.

**Comment by hsablonniere** [comment]
@zckrs Do you want to wait for an answer from someone else or should we close this issue?

**Comment by zckrs** [comment]
You can close if @markdalgleish have no comment or time `(=^ ◡ ^=)`
